# Generated by Django 4.1.3 on 2022-12-05 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_billingaddress_orderitem_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("abbr", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="States",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("abbr", models.CharField(max_length=10)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.countries"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.countries"
            ),
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.states"
            ),
        ),
    ]
