# Generated by Django 4.1.3 on 2022-12-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_billingaddress_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="slug",
            field=models.SlugField(default="-", unique=True),
        ),
    ]
