# Generated by Django 4.1.3 on 2022-12-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_products_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaddress",
            name="to_use",
            field=models.BooleanField(default=False),
        ),
    ]
